#!/usr/bin/env python3
"""
Replace the deployment section of README.md (lines 60 through the --- separator
before '## ⚙️ Environment Variables') with the new Apache2+Nginx+MySQL content.
"""
import sys

README = "/home/z/my-project/codebase-a/README.md"

with open(README, "r", encoding="utf-8") as f:
    content = f.read()

old_start_marker = "## 🚀 Quick Start — Ubuntu Server + Nginx + MySQL"
old_end_marker = "## ⚙️ Environment Variables"

start_idx = content.find(old_start_marker)
if start_idx == -1:
    print("ERROR: could not find start marker", file=sys.stderr)
    sys.exit(1)

end_idx = content.find(old_end_marker)
if end_idx == -1:
    print("ERROR: could not find end marker", file=sys.stderr)
    sys.exit(1)

search_back = content.rfind("\n---\n", 0, end_idx)
if search_back == -1:
    print("ERROR: could not find --- separator before Environment Variables", file=sys.stderr)
    sys.exit(1)

new_section = """## 🚀 Deployment — Ubuntu + Apache2 + Nginx + MySQL

iSecurify runs on a plain **Ubuntu 22.04 LTS** server — no Docker, no Coolify.
The deployment uses a four-layer stack:

```
┌────────────────────────────────────────────────────────────────────────┐
│                         Internet                                       │
└───────────────────────────┬────────────────────────────────────────────┘
                            │
                            ▼
┌────────────────────────────────────────────────────────────────────────┐
│  Apache2  (public edge, :80/:443, SSL via Let's Encrypt/certbot)       │
│  - Terminates TLS                                                       │
│  - Redirects HTTP → HTTPS                                              │
│  - Sets security headers (HSTS, CSP, X-Frame-Options, …)               │
└───────────────────────────┬────────────────────────────────────────────┘
                            │  ProxyPass http://127.0.0.1:8080/
                            ▼
┌────────────────────────────────────────────────────────────────────────┐
│  Nginx  (internal reverse proxy, 127.0.0.1:8080 only)                  │
│  - Static-asset caching (_next/static, brand icon)                     │
│  - Security headers (defense-in-depth)                                  │
│  - 50M upload limit                                                     │
└───────────────────────────┬────────────────────────────────────────────┘
                            │  proxy_pass http://127.0.0.1:3000
                            ▼
┌────────────────────────────────────────────────────────────────────────┐
│  Bun / Next.js  (systemd service, :3000)                               │
│  - Runs .next/standalone/server.js as the `isecurify` system user      │
│  - Reads env from /opt/isecurify/.env                                  │
│  - Logs to journald                                                     │
└───────────────────────────┬────────────────────────────────────────────┘
                            │  mysql2 driver
                            ▼
┌────────────────────────────────────────────────────────────────────────┐
│  MySQL 8.0  (localhost:3306)                                           │
│  - Database: isecurify                                                  │
│  - User: isecurify (random password, generated by deploy.sh)           │
└────────────────────────────────────────────────────────────────────────┘
```

> **Why two reverse proxies?** Apache2 is the public SSL terminator (it has the
> best certbot integration on Ubuntu). Nginx sits behind it as an internal
> layer for static-asset caching and security-header defense-in-depth. Both
> layers must be running for the app to be reachable from the internet.

### Prerequisites

- A fresh **Ubuntu 22.04 LTS** server (1 vCPU / 2 GB RAM minimum, 2 vCPU / 4 GB recommended)
- A **domain name** pointing at your server's public IP (A record, e.g. `isecurify.yourdomain.com → 1.2.3.4`)
- Ports **80** and **443** open in your firewall / cloud security group
- Root or sudo access
- (Optional) The repo uploaded to the server via rsync, or a git URL to clone from

### Step 1 — Upload the code to your server

If you have a git remote, the deploy script will clone it for you in Step 2 — skip ahead.

Otherwise, upload the project from your local machine:

```bash
# On your LOCAL machine — upload the project (rsync is fastest)
rsync -avz --exclude='node_modules' --exclude='.next' --exclude='.git' \\
      ./isecurify/  ubuntu@YOUR_SERVER_IP:/tmp/isecurify/

# On the SERVER — move it into place
ssh ubuntu@YOUR_SERVER_IP
sudo mkdir -p /opt/isecurify
sudo rsync -a /tmp/isecurify/ /opt/isecurify/
sudo chown -R $USER:$USER /opt/isecurify
cd /opt/isecurify
```

### Step 2 — Run the deploy script

The deploy script does **everything**: installs Apache2 + Nginx + MySQL + Bun, creates the `isecurify` system user, creates the MySQL database + user (with a random password), syncs the Prisma schema, builds the Next.js standalone bundle, writes `/opt/isecurify/.env`, installs + enables the systemd service, installs the Nginx internal config, installs the Apache2 edge config, and issues an SSL certificate via certbot.

```bash
# Option A: deploy from a git repo (recommended)
sudo bash deploy/scripts/deploy.sh isecurify.yourdomain.com  https://github.com/your-org/isecurify.git

# Option B: deploy from the code already on the server (run from inside the repo)
cd /opt/isecurify
sudo bash deploy/scripts/deploy.sh isecurify.yourdomain.com
```

The script will prompt for the MySQL root password (press **Enter** if you haven't set one yet — fresh Ubuntu 22.04 installs use `auth_socket` and `sudo mysql` works without a password).

The full deploy takes 5–10 minutes depending on server speed and network latency (most of it is `bun install` + `next build` + certbot's SSL issuance).

### Step 3 — Seed demo data (first time only)

The deploy script does **not** seed the database by default (so re-running it on an existing install won't clobber your data). To seed the demo tenant (Acme Corporation) + sample users + sample frameworks/controls/audits/clients/certificates:

```bash
# 1. Flip the SEED_DB flag to true
sudo sed -i 's/SEED_DB=false/SEED_DB=true/' /opt/isecurify/.env

# 2. Restart so the app picks up the new flag
sudo systemctl restart isecurify

# 3. Wait 10-15 seconds for the seed to complete (watch the logs)
sudo journalctl -u isecurify -f
#   → look for "✅ Seed complete." then Ctrl-C

# 4. Flip the flag back to false (so the seed doesn't re-run on next restart)
sudo sed -i 's/SEED_DB=true/SEED_DB=false/' /opt/isecurify/.env

# 5. Restart one more time to pick up the corrected flag
sudo systemctl restart isecurify
```

### Step 4 — Verify the deployment

```bash
# 1. All three services should be "active (running)"
sudo systemctl status isecurify nginx apache2

# 2. The app should respond on HTTPS
curl -I https://isecurify.yourdomain.com
#   → HTTP/2 200  (or 307 redirect to /login)

# 3. SSL certificate should be valid
curl -vI https://isecurify.yourdomain.com 2>&1 | grep -E "(subject|issuer|expire)"

# 4. MySQL should have all the iSecurify tables
sudo mysql -u isecurify -p isecurify -e "SHOW TABLES;"
#   → expect ~20 tables including Client, Certificate, ReminderLog, User, …

# 5. Tail the app logs in real time
sudo journalctl -u isecurify -f
```

Open `https://isecurify.yourdomain.com` in your browser and log in with one of the [default credentials](#-default-login-credentials) below.

### Step 5 — Updates

To redeploy after pushing new code to your git repo:

```bash
sudo bash /opt/isecurify/deploy/scripts/update.sh
```

This runs `git pull` → `bun install` → `bunx prisma db push` → `bun run build` → `systemctl restart isecurify`. Takes 2–4 minutes typically.

If you deployed without git (Option B in Step 2), re-upload the code with rsync and run:

```bash
cd /opt/isecurify
sudo rsync -a --exclude='node_modules' --exclude='.next' --exclude='.git' \\
           /tmp/isecurify/ ./
sudo bash deploy/scripts/update.sh
```

### Manual deployment (without the script)

If you prefer to deploy step-by-step instead of using `deploy.sh`, the four config files you need are:

| File | Install to | Purpose |
|------|-----------|---------|
| `deploy/systemd/isecurify.service` | `/etc/systemd/system/isecurify.service` | Runs `bun .next/standalone/server.js` as the `isecurify` user on port 3000 |
| `deploy/nginx/isecurify.conf` | `/etc/nginx/sites-available/isecurify` (+ symlink in `sites-enabled/`) | Internal reverse proxy on `127.0.0.1:8080` → `127.0.0.1:3000` |
| `deploy/apache/isecurify.conf` | `/etc/apache2/sites-available/isecurify.conf` (+ `a2ensite`) | Public edge on `:80/:443`, SSL termination, reverse proxy to `127.0.0.1:8080` |
| `.env.production.example` | copy to `/opt/isecurify/.env` and fill in real values | Database URL, NEXTAUTH_SECRET, app URL, etc. |

Then run, in order:

```bash
# 1. Install packages
sudo apt-get install -y curl git apache2 nginx mysql-server mysql-client \\
                        certbot python3-certbot-apache openssl rsync

# 2. Install Bun
curl -fsSL https://bun.sh/install | bash
sudo ln -sf ~/.bun/bin/bun /usr/local/bin/bun

# 3. Create the isecurify user + /opt/isecurify
sudo useradd --system --create-home --home-dir /opt/isecurify --shell /bin/bash isecurify
sudo mkdir -p /opt/isecurify/uploads
sudo chown -R isecurify:isecurify /opt/isecurify

# 4. Create the MySQL database + user
sudo mysql <<'SQL'
CREATE DATABASE isecurify CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'isecurify'@'localhost' IDENTIFIED BY 'STRONG_PASSWORD_HERE';
GRANT ALL PRIVILEGES ON isecurify.* TO 'isecurify'@'localhost';
FLUSH PRIVILEGES;
SQL

# 5. Copy the code to /opt/isecurify (rsync from your local machine, or git clone)
# 6. Write /opt/isecurify/.env from .env.production.example (fill in the MySQL password + generate NEXTAUTH_SECRET)
# 7. Build the app
cd /opt/isecurify
sudo -u isecurify bun install
sudo -u isecurify bunx prisma generate --schema prisma/schema.mysql.prisma
sudo -u isecurify bunx prisma db push --schema prisma/schema.mysql.prisma --accept-data-loss
sudo -u isecurify bun run build
sudo cp -r .next/static .next/standalone/.next/
sudo cp -r public .next/standalone/
sudo chown -R isecurify:isecurify .next

# 8. Install + start the systemd service
sudo cp deploy/systemd/isecurify.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now isecurify

# 9. Install + reload Nginx (internal, port 8080)
sudo cp deploy/nginx/isecurify.conf /etc/nginx/sites-available/isecurify
sudo ln -sf /etc/nginx/sites-available/isecurify /etc/nginx/sites-enabled/isecurify
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx

# 10. Install + reload Apache2 (edge, port 80/443)
sudo a2enmod proxy proxy_http ssl headers rewrite
sudo sed -i 's/isecurify.yourdomain.com/YOUR_REAL_DOMAIN/g' deploy/apache/isecurify.conf
sudo cp deploy/apache/isecurify.conf /etc/apache2/sites-available/isecurify.conf
sudo a2dissite 000-default
sudo a2ensite isecurify
sudo apache2ctl configtest && sudo systemctl reload apache2

# 11. Issue the SSL certificate
sudo certbot --apache -d YOUR_REAL_DOMAIN --redirect
sudo systemctl reload apache2
```

"""

new_content = content[:start_idx] + new_section + content[search_back + 1:]

with open(README, "w", encoding="utf-8") as f:
    f.write(new_content)

print("✓ README deployment section replaced successfully")
print(f"  Old section: {end_idx - start_idx} chars")
print(f"  New section: {len(new_section)} chars")
